[script_info]
script_name = "omni_lock"

# priority 1 to 10, 1 is the highest priority
live_cell_priority = 5 

[mainnet]
script = '''
{
    "args": "0x",
    "code_hash": "0x9b819793a64463aed77c615d6cb226eea5487ccfc0783043a587254cda2b6f26",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0xdfdb40f5d229536915f2d5403c66047e162e25dedd70a79ef5164356e1facdc8"
    }
}
'''

[testnet]
script = '''
{
    "args": "0x",
    "code_hash": "0xf329effd1c475a2978453c8600e1eaf0bc2087ee093c3ee64cc96ec6847752cb",
    "hash_type": "type"
}
'''
cell_dep = '''
{
    "dep_type": "code",
    "out_point": {
        "index": "0x0",
        "tx_hash": "0x27b62d8be8ed80b9f56ee0fe41355becdb6f6a40aeba82d3900434f43b1c8b60"
    }
}
'''
